<img src="http://www.digitalvidya.com/wp-content/uploads/2013/05/logoa5-300x95.png">

## Data Analytics using NumPy Assignment

In [1]:
import numpy as np

In [29]:
# 1.Create a rank 2 numpy array of random integers and print:a) shape,size and dimensions of the array b) number of odd and even
#   integers in the array
a=np.array(np.random.randint(10,size=(3,3)))
print(a.shape)
print(a.size)
print(a.ndim)

print(a)

b=np.where(a%2!=0,1,0)
print(np.count_nonzero(b))

(3, 3)
9
2
[[4 3 1]
 [4 6 8]
 [9 7 9]]
5


In [32]:
# 2.Create a (3X3) numpy array with values ranging from 1 to 9.
a=np.array(np.random.randint(10,size=(3,3)))
a

array([[7, 8, 4],
       [7, 3, 4],
       [6, 9, 2]])

In [41]:
# 3.Create a (5X5) random numpy array and print the numbers from the array which are greater than average value of the array.
# Hint: Use np.where() function
a=np.array(np.random.randint(10,size=(5,5)))
print(a)
avg=np.mean(a)
print(avg)
b=np.where(a>avg,a,None)
print(b)

[[5 8 4 7 8]
 [9 6 3 8 4]
 [6 6 7 3 7]
 [5 1 3 3 6]
 [6 9 8 6 5]]
5.72
[[None 8 None 7 8]
 [9 6 None 8 None]
 [6 6 7 None 7]
 [None None None None 6]
 [6 9 8 6 None]]


In [56]:
# 4.Given an array of random integers:
arr1 = np.random.randint(50,size=(10,10))
# Find out : a) row wise and column wise mean b) row wise and column wise max and min values c) Variance and Standard Deviation 
# of the array.
print(arr1)

row=arr1.mean(axis=0)
column=arr1.mean(axis=1)
print(row)
print(column)

row_min=np.amin(arr1,axis=1)
row_max=np.amax(arr1,axis=1)
print(row_min)
print(row_max)
column_min=np.amin(arr1,axis=0)
column_max=np.amax(arr1,axis=0)
print(column_min)
print(column_max)

print(np.std(arr1))
print(np.var(arr1))

[[23 43 22 19 40 32  6 46  0 23]
 [42 26 43 16  1 48 39 28 48  7]
 [41 48 26 43 22 23 23 35 29 28]
 [35 43 11  7 44 25 14 11  8 36]
 [28 45 46 12 34 15 24 23 23  6]
 [28 10  0 25 20 12 16 19 37 32]
 [24 32 49 44 29  4  7 36 23 45]
 [ 9 22 34  5 36  4 33 33 36 18]
 [32 28 47 23 34  6 44 46 11 24]
 [ 0  5  2 42 11 35 49  1  3 49]]
[26.2 30.2 28.  23.6 27.1 20.4 25.5 27.8 21.8 26.8]
[25.4 29.8 31.8 23.4 25.6 19.9 29.3 23.  29.5 19.7]
[ 0  1 22  7  6  0  4  4  6  0]
[46 48 48 44 46 37 49 36 47 49]
[0 5 0 5 1 4 6 1 0 6]
[42 48 49 44 44 48 49 46 48 49]
14.606587554935615
213.3524


In [60]:
# Extra Credits
# 5.Given two matrices:
arr1 = np.matrix([[4,5],[7,3]])
arr2 = np.matrix([[2,3],[8,9]])

# Find out the matrix multiplication of the above two matrices without using numpy function and then verify your answer 
# using np.dot(arr1,arr2) function
print(arr1)
print(arr2)
print(arr1*arr2)
print(np.dot(arr1,arr2))

[[4 5]
 [7 3]]
[[2 3]
 [8 9]]
[[48 57]
 [38 48]]
[[48 57]
 [38 48]]
